### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jbott** [FRC-3637-Daleks/2015-Documentation#1]
## Robot
- [ ] DiagRoboRIO
- [ ] Razor IMU
- [ ] Robot Application Tie ins
- [ ] MySQL script
## Vision Processing
- [x] Streaming images
- [ ] Overlay (for humans)
- [ ] Edge detection
- [ ] Automated control?
## NiceDash
- [ ] MQTT Console
- [ ] Widgets
- [ ] Streaming
## Pit Master
- [ ] Git server
- [ ] Tomcat Server
- [ ] Mysql Server
- [ ] MQTT Server?
## Pit Remotes
- [ ] Battery logger
- [ ] Secondary displays (Raspberry Pi?)
